---
sudo: required

notifications:
  email: true

services:
  - docker

before_script:
  - docker-compose -f docker-compose.yml up --build -d
  - docker ps -a
  - sleep 30

after_script:
  - docker-compose -f docker-compose.yml down

env:
  - DATA_SCI_PORT=8888 DATA_SCI_PATH=/home/travis
